services:
  - type: web
    name: flight-predictor-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 predictor_api:app
    autoDeploy: true
