name: Retrain Flight Model

on:
  schedule:
    - cron: '5 * * * *'    # Runs 5 minutes after the logger (hourly)
  workflow_dispatch:        # Manual trigger option

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install joblib pandas scikit-learn

    - name: Run retraining script
      run: |
        python retrain_model.py

    - name: Commit and push updated model and data
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://${GH_TOKEN}@github.com/singhan14/opensky-logger.git
        git add training_data.csv model.pkl
        git commit -m "🤖 Model retrained and updated at $(date -u +%Y-%m-%dT%H:%M:%SZ)" || echo "No changes"
        git push origin main
