name: Run Flight Count Prediction

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas joblib catboost

      - name: Run prediction script
        run: python prediction.py

      - name: Commit updated predictions
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add predictions/*.csv predictions/*.json
          git commit -m "Update flight count predictions"
          git push
        continue-on-error: true
